name: ${project.artifactId}-bukkit
main: ${project.groupId}.${project.artifactId}.bukkit.MinecraftAuthenticatorBukkit
version: ${project.version}
author: xXSchrandXx
description: WSC-Minecraft-Authenticator
api-version: 1.13
load: POSTWORLD
depends: [wscbridge-bungee]

commands:
  login:
    description: Command to log in.
  logout:
    description: Command to log out.
  wscauthenticator:
    description: Command for WSC-Minecraft-Authenticator.
    aliases:
    - wscauthenticatorbukkit
    - wscauth
    - wscauthbukkit
